name: pfa_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.5
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.30.0
  firebase_storage: ^11.2.4
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  random_string: ^2.3.1
  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/presentation/home/assets/icon/fire-truck.gif
    - lib/presentation/home/assets/icon/ambulance.gif
    - lib/presentation/home/assets/icon/police-car.gif
    - lib/presentation/home/assets/icon/car-crash.gif
    - lib/presentation/fire/assets/fire.gif
    - lib/presentation/fire/assets/fire-extinguisher.gif
    - lib/presentation/police/assets/police-car.gif
    - lib/presentation/police/assets/police.gif
    - lib/presentation/police/assets/security-guard.gif
  #   - images/a_dot_ham.jpeg
 